"""add phone number

Revision ID: 94916aac7fcd
Revises: 6dfa2bd06f0b
Create Date: 2023-05-01 12:30:58.749966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94916aac7fcd'
down_revision = '6dfa2bd06f0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
